const DEFAULT_EDO_INPUT_VALUE = "12"
const DEFAULT_MAX_NORM_INPUT_VALUE = "5"
const DEFAULT_MAX_RPD_INPUT_VALUE = "0.1"
const DEFAULT_PERIODS_INPUT_VALUE = "2"

export {
    DEFAULT_EDO_INPUT_VALUE,
    DEFAULT_MAX_NORM_INPUT_VALUE,
    DEFAULT_MAX_RPD_INPUT_VALUE,
    DEFAULT_PERIODS_INPUT_VALUE,
}
